# Generated by Django 6.1.1 on 2026-09-18 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Hospital', 'Hospital'), ('Ambulance', 'Ambulance'), ('Police', 'Police'), ('Fire Station', 'Fire Station'), ('Pharmacy', 'Pharmacy')], max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('Open 24 hours', 'Open 24 hours'), ('Available', 'Available'), ('Open now', 'Open now'), ('Closed', 'Closed')], default='Open now', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('destination', 'Destination'), ('emergency', 'Emergency')], max_length=20)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('destination_name', models.CharField(blank=True, max_length=255)),
                ('destination_address', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
