# Generated by Django 6.1.1 on 2026-09-26 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emergencycontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyservice',
            name='category',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Ambulance', 'Ambulance'), ('Police', 'Police'), ('Fire Station', 'Fire Station'), ('Pharmacy', 'Pharmacy'), ('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Mechanic', 'Mechanic'), ('Carpenter', 'Carpenter'), ('Locksmith', 'Locksmith'), ('Cleaning', 'Cleaning Service'), ('Pest Control', 'Pest Control'), ('Taxi', 'Taxi'), ('Towing', 'Towing Service'), ('Veterinary', 'Veterinary')], max_length=30),
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sos', 'SOS Emergency'), ('medical', 'Medical Emergency'), ('accident', 'Accident'), ('safety', 'Safety Emergency'), ('custom', 'Custom')], default='sos', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('message', models.TextField()),
                ('recipient', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.emergencyalert')),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.emergencycontact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
