# Generated by Django 6.1.1 on 2026-09-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_emergencyalert_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
        ),
    ]
