# Generated by Django 6.1.1 on 2026-09-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_emergencyalert_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
