# Generated by Django 6.1.1 on 2026-09-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_devicetoken_sessionlog_tokenblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyservice',
            name='category',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Ambulance', 'Ambulance'), ('Police', 'Police'), ('Fire Station', 'Fire Station'), ('Pharmacy', 'Pharmacy'), ('Mechanic', 'Mechanic')], max_length=30),
        ),
    ]
